favicon: null
cta:
  bucket: null
  version: null
  domain: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.3647016717586666
  brandStrength: 0.9984199169557542
  rhythmicContrast: 0.7183166614267975
  brandColors:
    - '#FFFFFF'
    - '#BB252E'
    - '#1A1919'
    - '#C4C4C4'
    - '#464545'
  lightness: 0.6236936512868851
typography_spectrum: 0.3530466
layout_spectrum: 0.2903226
analytics:
  twitter: null
  google: null
  facebook: null
name: I ♥️ Startup
